artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/niharika41298/yoga-poses-dataset/download?datasetVersionNumber=1
  local_data_file: artifacts/data_ingestion/yoga_poses.zip
  unzip_dir: artifacts/data_ingestion


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5