artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/niharika41298/yoga-poses-dataset/download?datasetVersionNumber=1
  local_data_file: artifacts/data_ingestion/yoga_poses.zip
  unzip_dir: artifacts/data_ingestion

data_extraction:
  root_dir: artifacts/data_extraction
  extracted_data: artifacts/data_extraction/extracted_data


prepare_model:
  root_dir: artifacts/prepare_base_model
  model_path: artifacts/prepare_base_model/base_model.h5
  updated_model_path: artifacts/prepare_base_model/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  updated_base_model_path: artifacts/prepare_base_model/model.h5



prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras