artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/niharika41298/yoga-poses-dataset/download?datasetVersionNumber=1
  local_data_file: artifacts/data_ingestion/yoga_poses.zip
  unzip_dir: artifacts/data_ingestion